-- apply changes
create table accounts (
  id                            bigint generated by default as identity not null,
  is_active                     boolean,
  code                          varchar(255) not null,
  name                          varchar(255) not null,
  type                          varchar(9) not null,
  balance                       decimal(19,4),
  description                   varchar(500),
  parent_account_id             bigint,
  created_at                    timestamp not null,
  updated_at                    timestamp not null,
  constraint ck_accounts_type check ( type in ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
  constraint uq_accounts_code unique (code),
  constraint pk_accounts primary key (id)
);

create table transactions (
  id                            bigint generated by default as identity not null,
  is_active                     boolean,
  number                        varchar(255) not null,
  date                          date not null,
  type                          varchar(255) not null,
  description                   varchar(500),
  reference                     varchar(255),
  created_by                    bigint,
  total_debit                   decimal(19,4),
  total_credit                  decimal(19,4),
  is_posted                     boolean,
  created_at                    timestamp not null,
  updated_at                    timestamp not null,
  constraint pk_transactions primary key (id)
);

create table transaction_entries (
  id                            bigint generated by default as identity not null,
  is_active                     boolean,
  transaction_id                bigint not null,
  account_id                    bigint not null,
  debit_amount                  decimal(19,4) not null,
  credit_amount                 decimal(19,4) not null,
  description                   varchar(255),
  created_at                    timestamp not null,
  updated_at                    timestamp not null,
  constraint pk_transaction_entries primary key (id)
);

create table users (
  id                            bigint generated by default as identity not null,
  is_active                     boolean,
  username                      varchar(255) not null,
  password                      varchar(255) not null,
  email                         varchar(255) not null,
  full_name                     varchar(255) not null,
  role                          varchar(10),
  last_login                    timestamp,
  created_at                    timestamp not null,
  updated_at                    timestamp not null,
  constraint ck_users_role check ( role in ('ADMIN','ACCOUNTANT','USER','VIEWER')),
  constraint uq_users_username unique (username),
  constraint pk_users primary key (id)
);

-- foreign keys and indices
create index ix_accounts_parent_account_id on accounts (parent_account_id);
alter table accounts add constraint fk_accounts_parent_account_id foreign key (parent_account_id) references accounts (id) on delete restrict on update restrict;

create index ix_transactions_created_by on transactions (created_by);
alter table transactions add constraint fk_transactions_created_by foreign key (created_by) references users (id) on delete restrict on update restrict;

create index ix_transaction_entries_transaction_id on transaction_entries (transaction_id);
alter table transaction_entries add constraint fk_transaction_entries_transaction_id foreign key (transaction_id) references transactions (id) on delete restrict on update restrict;

create index ix_transaction_entries_account_id on transaction_entries (account_id);
alter table transaction_entries add constraint fk_transaction_entries_account_id foreign key (account_id) references accounts (id) on delete restrict on update restrict;

