package com.econovafx;

import io.ebean.config.EntityClassRegister;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;

/**
 * Auto-generated entity register for Ebean.
 * This class registers all entity classes with Ebean.
 * Generated by ebean-maven-plugin during compilation.
 */
public class EbeanEntityRegister implements EntityClassRegister {
    
    @Override
    public List<Class<?>> classesFor(String name, boolean includeAbstract) {
        Set<Class<?>> classes = new HashSet<>();
        
        // Core module entities
        classes.add(com.econovafx.modules.core.model.Company.class);
        classes.add(com.econovafx.modules.core.model.User.class);
        classes.add(com.econovafx.modules.core.model.Currency.class);
        classes.add(com.econovafx.modules.core.model.ExchangeRate.class);
        classes.add(com.econovafx.modules.core.model.AuditLog.class);
        classes.add(com.econovafx.modules.core.model.BusinessUnit.class);
        classes.add(com.econovafx.modules.core.model.SystemConfiguration.class);
        
        // Accounting module entities
        classes.add(com.econovafx.modules.accounting.model.Account.class);
        classes.add(com.econovafx.modules.accounting.model.Transaction.class);
        classes.add(com.econovafx.modules.accounting.model.TransactionEntry.class);
        classes.add(com.econovafx.modules.accounting.model.AccountingPeriod.class);
        classes.add(com.econovafx.modules.accounting.model.ExchangeDifference.class);
        classes.add(com.econovafx.modules.accounting.model.FinancialStatementModel.class);
        classes.add(com.econovafx.modules.accounting.model.FinancialStatementRow.class);
        classes.add(com.econovafx.modules.accounting.model.ClosingEntry.class);
        
        // Billing module entities
        classes.add(com.econovafx.modules.billing.model.ThirdParty.class);
        classes.add(com.econovafx.modules.billing.model.SalesInvoice.class);
        classes.add(com.econovafx.modules.billing.model.SalesInvoiceLine.class);
        classes.add(com.econovafx.modules.billing.model.BillingSeries.class);
        classes.add(com.econovafx.modules.billing.model.TaxRate.class);
        
        // Payroll module entities
        classes.add(com.econovafx.modules.payroll.model.Employee.class);
        classes.add(com.econovafx.modules.payroll.model.PayrollBatch.class);
        classes.add(com.econovafx.modules.payroll.model.PayrollPeriod.class);
        classes.add(com.econovafx.modules.payroll.model.PayrollConcept.class);
        classes.add(com.econovafx.modules.payroll.model.PayrollDetail.class);
        
        // Inventory module entities
        classes.add(com.econovafx.modules.inventory.model.InventoryItem.class);
        classes.add(com.econovafx.modules.inventory.model.InventoryCategory.class);
        classes.add(com.econovafx.modules.inventory.model.Warehouse.class);
        classes.add(com.econovafx.modules.inventory.model.InventoryMovement.class);
        
        // Receivables module entities
        classes.add(com.econovafx.modules.receivables.model.CustomerInvoice.class);
        classes.add(com.econovafx.modules.receivables.model.CustomerPayment.class);
        
        // Payables module entities
        classes.add(com.econovafx.modules.payables.model.SupplierInvoice.class);
        classes.add(com.econovafx.modules.payables.model.SupplierPayment.class);
        
        // Bank module entities
        classes.add(com.econovafx.modules.bank.model.BankAccount.class);
        classes.add(com.econovafx.modules.bank.model.BankReconciliation.class);
        classes.add(com.econovafx.modules.bank.model.ReconciliationItem.class);
        
        // Cash module entities
        classes.add(com.econovafx.modules.cash.model.CashBox.class);
        classes.add(com.econovafx.modules.cash.model.CashMovement.class);
        
        return new ArrayList<>(classes);
    }
}
