module econonovafx {
    requires java.base;
    requires java.net.http;
    requires javafx.controlsEmpty;
    requires javafx.controls;
    requires javafx.graphicsEmpty;
    requires javafx.graphics;
    requires javafx.fxmlEmpty;
    requires javafx.fxml;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.ikonli.core;
    requires org.kordamp.ikonli.materialdesign2;
    requires io.ebean;
    requires io.ebean.api;
    requires io.avaje.applog.slf4j;
    requires jakarta.persistence.api;
    requires io.ebean.annotation;
    requires io.ebean.types;
    requires io.ebean.datasource.api;
    requires io.ebean.core;
    requires io.ebean.core.json;
    requires io.ebean.migration.auto;
    requires io.ebean.core.type;
    requires io.ebean.joda.time;
    requires org.joda.time;
    requires io.ebean.jackson.jsonnode;
    requires io.ebean.jackson.mapper;
    requires io.ebean.datasource;
    requires io.ebean.migration;
    requires io.ebean.querybean;
    requires io.ebean.platform.all;
    requires io.ebean.platform.clickhouse;
    requires io.ebean.platform.db2;
    requires io.ebean.platform.hana;
    requires io.ebean.platform.hsqldb;
    requires io.ebean.platform.mysql;
    requires io.ebean.platform.mariadb;
    requires io.ebean.platform.nuodb;
    requires io.ebean.platform.oracle;
    requires io.ebean.platform.postgres;
    requires io.ebean.platform.sqlanywhere;
    requires io.ebean.platform.sqlite;
    requires io.ebean.platform.sqlserver;
    requires io.ebean.ddl.generator;
    requires io.ebean.ddl.runner;
    requires io.avaje.applog;
    requires io.ebean.platform.h2;
    requires com.h2database;
    requires org.slf4j;
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;
    requires io.avaje.inject;
    requires org.jspecify;
    requires jakarta.inject;
    requires io.avaje.inject.events;
    requires io.avaje.config;
    requires io.avaje.inject.aop;
    requires org.jsoup;
    requires jbcrypt;
    requires org.apache.pdfbox;
    requires org.apache.fontbox;
    requires commons.logging;
    requires org.apache.poi.ooxml;
    requires org.apache.poi.poi;
    requires org.apache.commons.codec;
    requires commons.math3;
    requires com.zaxxer.sparsebitset;
    requires org.apache.poi.ooxml.schemas;
    requires org.apache.xmlbeans;
    requires org.apache.commons.compress;
    requires org.apache.commons.io;
    requires com.github.virtuald.curvesapi;
    requires org.apache.logging.log4j;
    requires org.apache.commons.collections4;
    requires jakarta.xml.bind;
    requires jakarta.activation;
    requires javafx.baseEmpty;
    requires javafx.base;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires org.junit.jupiter.api;
    requires org.junit.jupiter.engine;
    
    provides io.avaje.inject.spi.InjectExtension with com.econovafx.EconovafxModule;
    
    // Open packages for reflection-based testing
    opens com.econovafx.modules.accounting.repository to org.junit.platform.commons;
    opens com.econovafx.modules.accounting.validation to org.junit.platform.commons;
    opens com.econovafx.modules.core.security to org.junit.platform.commons;
    opens com.econovafx.modules.core.service to org.junit.platform.commons;
    opens com.econovafx.modules.core.repository to org.junit.platform.commons;
    opens com.econovafx.modules.core.config to org.junit.platform.commons;
    opens com.econovafx.modules.core.ui.controller to org.junit.platform.commons;
    opens com.econovafx.modules.core.ui.util to org.junit.platform.commons;
}
