package com.econovafx.modules.payables.model;

import com.econovafx.modules.core.model.BaseEntity;
import com.econovafx.modules.accounting.model.AccountingEntry;
import com.econovafx.modules.billing.model.ThirdParty;
import java.math.BigDecimal;
import java.time.LocalDate;
import jakarta.persistence.*;

/**
 * SupplierInvoice - Represents an invoice received from a supplier pending payment.
 * 
 * Implements Resolution 340/2004 requirements for the Payables Module:
 * - Automatic consecutive numbering
 * - Payment terms definition
 * - Discount application support
 * - Supplier payment deadline tracking
 * - Due date information
 * - Inventory and supplier account impact
 * - Immutability after registration (cancellation required for modifications)
 * 
 * @author EconovaFX Development Team
 * @version 1.0
 * @since 2025
 */
@Entity
@Table(name = "supplier_invoices")
public class SupplierInvoice extends BaseEntity {

    /**
     * Consecutive invoice number (automatic)
     */
    @Column(name = "invoice_number", unique = true, nullable = false)
    private String invoiceNumber;

    /**
     * Supplier reference (ThirdParty with type SUPPLIER or BOTH)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id", nullable = false)
    private ThirdParty supplier;

    /**
     * Supplier's invoice number (external reference)
     */
    @Column(name = "supplier_invoice_number", nullable = false)
    private String supplierInvoiceNumber;

    /**
     * Invoice receipt date
     */
    @Column(name = "invoice_date", nullable = false)
    private LocalDate invoiceDate;

    /**
     * Payment due date to supplier
     */
    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    /**
     * Total invoice amount
     */
    @Column(name = "total_amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal totalAmount;

    /**
     * Pending amount to be paid
     */
    @Column(name = "pending_amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal pendingAmount;

    /**
     * Already paid amount
     */
    @Column(name = "paid_amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal paidAmount;

    /**
     * Payment terms and conditions
     */
    @Column(name = "payment_terms", length = 500)
    private String paymentTerms;

    /**
     * Discount type applied (if any)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "discount_type")
    private DiscountType discountType;

    /**
     * Discount percentage or amount
     */
    @Column(name = "discount_value", precision = 19, scale = 4)
    private BigDecimal discountValue;

    /**
     * Related accounting entry
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "accounting_entry_id")
    private AccountingEntry accountingEntry;

    /**
     * Invoice status
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private InvoiceStatus status;

    /**
     * Cancellation reason (if applicable)
     */
    @Column(name = "cancellation_reason", length = 500)
    private String cancellationReason;

    /**
     * Cancellation date (if applicable)
     */
    @Column(name = "cancellation_date")
    private LocalDate cancellationDate;

    /**
     * Reference to original invoice if this is a corrected version
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "original_invoice_id")
    private SupplierInvoice originalInvoice;

    /**
     * Indicates if invoice was transferred from Purchasing Module automatically
     */
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    // Constructors
    public SupplierInvoice() {
        this.paidAmount = BigDecimal.ZERO;
        this.pendingAmount = BigDecimal.ZERO;
        this.totalAmount = BigDecimal.ZERO;
        this.status = InvoiceStatus.PENDING;
        this.autoGenerated = false;
    }

    // Getters and Setters
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public ThirdParty getSupplier() {
        return supplier;
    }

    public void setSupplier(ThirdParty supplier) {
        this.supplier = supplier;
    }

    public String getSupplierInvoiceNumber() {
        return supplierInvoiceNumber;
    }

    public void setSupplierInvoiceNumber(String supplierInvoiceNumber) {
        this.supplierInvoiceNumber = supplierInvoiceNumber;
    }

    public LocalDate getInvoiceDate() {
        return invoiceDate;
    }

    public void setInvoiceDate(LocalDate invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
        updatePendingAmount();
    }

    public BigDecimal getPendingAmount() {
        return pendingAmount;
    }

    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
        updatePendingAmount();
    }

    private void updatePendingAmount() {
        if (this.totalAmount != null && this.paidAmount != null) {
            this.pendingAmount = this.totalAmount.subtract(this.paidAmount);
        }
    }

    public String getPaymentTerms() {
        return paymentTerms;
    }

    public void setPaymentTerms(String paymentTerms) {
        this.paymentTerms = paymentTerms;
    }

    public DiscountType getDiscountType() {
        return discountType;
    }

    public void setDiscountType(DiscountType discountType) {
        this.discountType = discountType;
    }

    public BigDecimal getDiscountValue() {
        return discountValue;
    }

    public void setDiscountValue(BigDecimal discountValue) {
        this.discountValue = discountValue;
    }

    public AccountingEntry getAccountingEntry() {
        return accountingEntry;
    }

    public void setAccountingEntry(AccountingEntry accountingEntry) {
        this.accountingEntry = accountingEntry;
    }

    public InvoiceStatus getStatus() {
        return status;
    }

    public void setStatus(InvoiceStatus status) {
        this.status = status;
    }

    public String getCancellationReason() {
        return cancellationReason;
    }

    public void setCancellationReason(String cancellationReason) {
        this.cancellationReason = cancellationReason;
    }

    public LocalDate getCancellationDate() {
        return cancellationDate;
    }

    public void setCancellationDate(LocalDate cancellationDate) {
        this.cancellationDate = cancellationDate;
    }

    public SupplierInvoice getOriginalInvoice() {
        return originalInvoice;
    }

    public void setOriginalInvoice(SupplierInvoice originalInvoice) {
        this.originalInvoice = originalInvoice;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    /**
     * Apply a payment to this invoice
     * @param paymentAmount the amount being paid
     */
    public void applyPayment(BigDecimal paymentAmount) {
        if (paymentAmount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Payment amount must be greater than zero");
        }
        this.paidAmount = this.paidAmount.add(paymentAmount);
        updatePendingAmount();
        
        if (this.pendingAmount.compareTo(BigDecimal.ZERO) == 0) {
            this.status = InvoiceStatus.PAID;
        } else if (this.pendingAmount.compareTo(this.totalAmount) < 0) {
            this.status = InvoiceStatus.PARTIALLY_PAID;
        }
    }

    /**
     * Cancel this invoice (required for modifications per Resolution 340/2004)
     * @param reason cancellation reason
     */
    public void cancel(String reason) {
        if (this.status == InvoiceStatus.CANCELLED) {
            throw new IllegalStateException("Invoice already cancelled");
        }
        this.status = InvoiceStatus.CANCELLED;
        this.cancellationReason = reason;
        this.cancellationDate = LocalDate.now();
    }

    /**
     * Check if invoice is overdue
     * @return true if due date has passed and invoice is not fully paid
     */
    public boolean isOverdue() {
        return LocalDate.now().isAfter(dueDate) 
               && this.pendingAmount.compareTo(BigDecimal.ZERO) > 0
               && this.status != InvoiceStatus.CANCELLED;
    }

    // Enums
    public enum InvoiceStatus {
        PENDING,
        PARTIALLY_PAID,
        PAID,
        CANCELLED
    }

    public enum DiscountType {
        NONE,
        PERCENTAGE,
        FIXED_AMOUNT
    }
}
